version: '3'
services:
    dockvue:
        build:
            context: .
            dockerfile:  ./dockerfiles/dockvue.dockerfile
        image: jacobrepo/dockvue:0.01
        user: "${UID}:${GID}"
        expose:
        - 80
        - 8080
        - 8000
        ports:
        - "10080:80"
        - "18080:8080"
        - "18000:8000"
        volumes:
        - /home/jacob_shih/volumes/repo/dockvue:/home/node/dockvue:Z
        working_dir: /home/node/dockvue
        dns:
        - 172.19.10.100
        - 172.19.10.99
        container_name: dockvue
        entrypoint: /bin/sh
        stdin_open: true
        tty: true

