version: '3'
services:
    myreact:
        build:
            context: .
            dockerfile:  ./dockerfiles/react.dockerfile
        image: utara/myreact:0.01
        user: "${UID}:${GID}"
        expose:
        - 80
        - 8080
        - 8000
        - 3000
        - 5000
        ports:
        - "10080:80"
        - "8080:8080"
        - "8000:8000"
        - "3000:3000"
        - "5000:5000"
        volumes:
        - ~/volumes/utara/myreact:/home/user/myreact
        working_dir: /home/user/myreact
        container_name: myreact
        entrypoint: /bin/sh
        stdin_open: true
        tty: true

